name: Generate Scan Report

on:
  schedule:
    # Every Friday at 16:30 UTC
    - cron: '30 16 * * 5'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: ministryofjustice/opg-repository-scanner@latest
